version: '3'

services:
  springboot-app:
    container_name: spring-app
    image: springbooot-app
    restart: always
    build: ./sprintboot-backend
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
    - MyAppNet

    #database
  mysqldb: 
    container_name: mysqldb
    image: mysql:8.0
    ports: 
      - 3306:3306   
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - MyAppNet

   

  # Frontend
  angular-service:
    container_name: angular-container
    build: ./SpintBootFront
    ports:
      - "4200:4200"
    command: >
      bash -c "npm start"
    environment:
      BACKEND_URL: http://spring-app:8080
    depends_on:
      - springboot-app
    networks:
      - MyAppNet


networks:
  MyAppNet:
   driver: bridge
