name: Update Submodules

on:
  repository_dispatch:
    types:
      - update_submodules

jobs:
  update-references:
    runs-on: ubuntu-latest

    steps:
    # Checkout the main repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Set up SSH key for accessing private repositories or submodules
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Update submodules and push changes back to the repository
    - name: Update submodules
      run: |
        git submodule update --remote --merge
        git commit -am "Update submodule references"
        git push origin main
